settings:
  visible_browser: true  # Set to false for headless mode
  delay_min: 10  # Minimum wait time (in seconds) between requests
  delay_max: 30  # Maximum wait time (in seconds) between requests
  recursion_depth: 1  # How deep to scrape followers (0 = no recursion)
  follower_scrape_limit: 500  # Stop scraping when this many usernames are collected

seed_usernames:
  - gsmplusvrsac
  - iphone.miami
