# config.yaml

settings:
  delay_min: 5
  delay_max: 10
  follower_scrape_limit: 5
  unlimited_follower_scrape: False
  scroll_attempts_max: 20
  recursion_depth: 1
  visible_browser: false # Set to False for headless (invisible) browser operation

keywords:
  - "celulares"
  - "accesorios"
  - "mayorista"
  - "distribuidor"
  - "smartphone"
  - "movil"
  - "telefone"
  - "tecnologia"
  - "gadgets"
  - "electronics"
  - "smartphones"
  - "mobile"
  - "tech"
  - "gadget"
  - "mobile shop"
  - "mobile store"

  
# REQUIRED: List of Instagram usernames to start scraping from.

seed_usernames:
  - "quality_gadgets_hub"
  - "mobile_shop_latam"

# REQUIRED: List of user agents for the browser.
# The scraper will randomly pick one from this list for each session.
# Having multiple user agents can help avoid detection.
user_agents:
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edge/108.0.1462.54"
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Firefox/108.0"
  # Add more user agents here if desired.

export_settings:
  enabled_formats:
    - "csv"
    # - "excel"
    # - "airtable"
    # - "google_sheets"
  
  csv_filename: "instagram_leads.csv"
  excel_filename: "instagram_leads.xlsx"

  airtable:
    table_name: "Instagram Leads"

  google_sheets:
    credentials_file: "google_sheets_service_account.json"
    sheet_name: "Instagram Leads"